### ISSUE TITLE
Centos 6 i386 nodejs 4.1 won't build

### ISSUE THREAD

**Issue by manfer** [kazuhisya/nodejs-rpm#42]
I'm trying to build the new version of nodejs in an i386 machine running Centos 6.7.

The problem is that Centos 6 doesn't fulfill at least the requirements gcc4.8 nor python2.7.

I have installed devtoolset-3 Software Collection that allows me to use gcc4.9.1 and a virtual environtment with python3.4. And still unable to build.

```
+ '[' -z x86 ']'
+ ./configure --shared-openssl --shared-openssl-includes=/usr/include --shared-zlib --shared-zlib-includes=/usr/include
  File "./configure", line 427
    '''
      ^
SyntaxError: Missing parentheses in call to 'print'
error: Estado de salida erróneo de /var/tmp/rpm-tmp.4zlcZ1 (%build)
```

This is the next error I'm getting. Not sure if this is because of other requirement that is not available in the system or a bug in nodejs and how to solve it. It is the third error and stopped trying by now.

I think buildrequires allows to specify a version so in my opinion the spec should be updated. Don't know which is the correct systems but if possible the version requirement should be specified on the spec so when running yum-builddep it complains about missing requirements.

**Comment by manfer** [comment]
Reading the error more carefully I realized that has to do with using python3.4. So I created a virtual environtment with python2.7 instead and I'm retrying the build.

So the requirerements that at least are not available in Centos 6.7 are gcc >= 4.8 and python = 2.7

I think it will build now. Still waiting for it to finish.

**Comment by manfer** [comment]
It was builded fine so those are the requirements gcc >= 4.8 and python 2.7. The rest of required packages can be installed from Centos6 repositories.

**Comment by kazuhisya** [comment]
Sorry. We do not support 32bit environment.
Because RedHat and CentOS does not provide `devtoolset-3` and `SCL` repository for i386/i686.
And one additional reason, I can not support that your own build gcc and python.

btw.
As a result of reviewing the process, I noticed that I can not build even in el6 x86_64. I'll fix in the near future.

**Comment by manfer** [comment]
If the system meets the requirements it will build with current spec. Thanks.
