### ISSUE TITLE
CentOS6 x86_64 won't build

### ISSUE THREAD

**Issue by kazuhisya** [kazuhisya/nodejs-rpm#43]
```
WARNING: C++ compiler too old, need g++ 4.8 or clang++ 3.4 (CXX=g++)
```

**Comment by manfer** [comment]
I don't think this is correct. The requirement is g++ 4.8 or clang++ 3.4 and not devtoolset-3

Installing devtoolset-3 SCL is a way to fulfill that requirement but not the only way.

The same with python2.7. How people decide to install that package is up to them. And for sure python2.7 SCL is not the only way.

For same reason, in my opinion, it is not the task of the spec to enable the scls with source command.

I have not tried but I think with this change the spec will not work for anyone that has installed g++ and/or python2.7 in a different way than with Software Collections.

**Comment by kazuhisya** [comment]
> Installing devtoolset-3 SCL is a way to fulfill that requirement but not the only way.

Yes, you are correct.
But, devtoolset and scl are (semi-)official repository that are supported on Red Hat and CentOS Project.

In my opinion, it use quite natural a lot when newer gcc(and python) is required.

> It is ok to suggest in the documentation to install devtoolset-3 but forcing it on spec is not good in my opinion.

Agree.
People who use it and otherwise... Do you have any implementation both become happy?

**Comment by manfer** [comment]
After investigating more on spec files syntax I have to say it doesn't seem to be easy to do it different than what you are doing.

To do something different it seems you would need to remove the BuildRequires for python and devtoolset-3 and find a way to check things programatically in the preparation phase or before. Or in the make file.

For python maybe it is not so difficult to check that `python --version` returns a valid python instance to proceed with the build. For g++ or clang++ don't know how to do it.

**Comment by kazuhisya** [comment]
ok, `SCL` and `devtools` is no longer needed in BuildRequires.  (4e519346976535bcd947f18c3b31db6a77deb73a)
you have to be set as a shell environment variable when you run make.

**Comment by manfer** [comment]
Thanks. That's great.
