### ISSUE TITLE
Following el5 spectool directions yields certificate error

### ISSUE THREAD

**Issue by victor73** [kazuhisya/nodejs-rpm#48]
spectool -g nodejs-4.2.spec 
  --2015-10-17 18:17:40--  https://nodejs.org/dist/v4.2.1/node-v4.2.1.tar.gz
  Resolving nodejs.org... 104.20.23.46, 104.20.22.46, 2400:cb00:2048:1::6814:162e, ...
  Connecting to nodejs.org|104.20.23.46|:443... connected.
  ERROR: certificate common name `*.nodejs.org' doesn't match requested host name `nodejs.org'.
  To connect to nodejs.org insecurely, use `--no-check-certificate'.
  Unable to establish SSL connection.

A workaround is to change the url in the spec file to http:// instead of https://

**Comment by kazuhisya** [comment]
This is el5 `wget`'s known issues.(`spectool` run `wget` inside.)
[Bug 903756 – Wget doesn't recognize the certificate with alternative names](https://bugzilla.redhat.com/show_bug.cgi?id=903756)

Therefore, I decided to write a workaround in the `README`.
