### ISSUE TITLE
Issue building on Centos5

### ISSUE THREAD

**Issue by victor73** [kazuhisya/nodejs-rpm#49]
After installing the various dependencies, per the README, and invoking rpmbuild through scl, the build fails as follows:

...
  LD_LIBRARY_PATH=/root/rpmbuild/BUILD/node-v5.0.0/out/Release/lib.host:/root/rpmbuild/BUILD/node-v5.0.0/out/Release/lib.target:$LD_LIBRARY_PATH; export LD_LIBRARY_PATH; cd ../deps/v8/tools/gyp; mkdir -p /root/rpmbuild/BUILD/node-v5.0.0/out/Release/obj/gen; python2.7 ../../tools/js2c.py "/root/rpmbuild/BUILD/node-v5.0.0/out/Release/obj/gen/experimental-libraries.cc" EXPERIMENTAL ../../src/macros.py ../../src/messages.h ../../src/proxy.js ../../src/generator.js ../../src/harmony-atomics.js ../../src/harmony-array-includes.js ../../src/harmony-concat-spreadable.js ../../src/harmony-tostring.js ../../src/harmony-regexp.js ../../src/harmony-reflect.js ../../src/harmony-spread.js ../../src/harmony-object.js ../../src/harmony-object-observe.js ../../src/harmony-sharedarraybuffer.js ../../src/harmony-simd.js
  LD_LIBRARY_PATH=/root/rpmbuild/BUILD/node-v5.0.0/out/Release/lib.host:/root/rpmbuild/BUILD/node-v5.0.0/out/Release/lib.target:$LD_LIBRARY_PATH; export LD_LIBRARY_PATH; cd ../deps/v8/tools/gyp; mkdir -p /root/rpmbuild/BUILD/node-v5.0.0/out/Release/obj/gen; python ../../tools/js2c.py "/root/rpmbuild/BUILD/node-v5.0.0/out/Release/obj/gen/code-stub-libraries.cc" CODE_STUB ../../src/macros.py ../../src/messages.h ../../src/code-stubs.js
  File "../../tools/js2c.py", line 441
    except Error as e:
                  ^
SyntaxError: invalid syntax
make[2]: *** [/root/rpmbuild/BUILD/node-v5.0.0/out/Release/obj/gen/code-stub-libraries.cc] Error 1
make[2]: *** Waiting for unfinished jobs....
/tmp/ccrffLjk.s: Assembler messages:
/tmp/ccrffLjk.s:5611: Error: expecting string instruction after `rep'
/tmp/ccrffLjk.s:5651: Error: expecting string instruction after `rep'
make[2]: *** [/root/rpmbuild/BUILD/node-v5.0.0/out/Release/obj.target/gtest/deps/gtest/src/gtest.o] Error 1
make[2]: Leaving directory `/root/rpmbuild/BUILD/node-v5.0.0/out'
make[1]: *** [node] Error 2
make[1]: Leaving directory `/root/rpmbuild/BUILD/node-v5.0.0'
make: *** [node-v5.0.0-linux-x64.tar] Error 2
error: Bad exit status from /var/tmp/rpm-tmp.56228 (%build)

RPM build errors:
    Bad exit status from /var/tmp/rpm-tmp.56228 (%build)

**Comment by kazuhisya** [comment]
`/tools/js2c.py` seems has been added recently.
Fixed: 7d271e086542febbd41f03f574d5f5c56df57044
