### ISSUE TITLE
LICENSE file

### ISSUE THREAD

**Issue by hnakamur** [kazuhisya/nodejs-rpm#50]
First of all, thanks for sharing nice spec files!

Could you add LICENSE file?

The following pages might help for choosing a license.
* [Githubによる、オープンソースライセンスの選び方 | オープンソース・ライセンスの談話室](http://www.catch.jp/oss-license/2013/09/10/github/)
* [Choosing an open source license doesn’t need to be scary - Choose a License](http://choosealicense.com/)

Thanks!

**Comment by kazuhisya** [comment]
Fiexd:  86dda8419fda7951c07292fabfb054aae964a2d2

**Comment by hnakamur** [comment]
Thanks! :+1:
