### ISSUE TITLE
md5 error in LTS make

### ISSUE THREAD

**Issue by ZissisT** [kazuhisya/nodejs-rpm#58]
Hello,

When trying 'make' in LTS branch (4.5.0) I get an md5 mismatch error:

rm -rf node-v4.5.0-linux-x64
rm -rf out/deps out/Release
/usr/bin/python ./configure \
        --prefix=/ \
        --dest-cpu=x64 \
        --tag= \
        --release-urlbase= \
         --download=all --with-intl=small-icu
creating  ./icu_config.gypi
* ECMA-402 (Intl) support didn't find ICU in ./deps/icu..
 <https://ssl.icu-project.org/files/icu4c/56.1/icu4c-56_1-src.zip>
 Fetch: : 0.0MB total, 0.0MB downloaded
 MD5:      01b1e4427b5a406a73ceaa64dab85e12  ./deps/icu4c-56_1-src.zip
 Expected: 61d71888f14bf00cc3e8a6f2c087d367      *MISMATCH*

 ** Corrupted ZIP? Delete ./deps/icu4c-56_1-src.zip to retry download.

 Cannot build Intl without ICU in ./deps/icu.
 (Fix, or disable with "--with-intl=none" )
Makefile:558: recipe for target 'node-v4.5.0-linux-x64.tar' failed
make[1]: *** [node-v4.5.0-linux-x64.tar] Error 1

Is there anything else that I need to do ?

Using SLES12

Thank you

**Comment by kazuhisya** [comment]
Hi, @ZissisT
I'm sorry, I don't have SLES. I try to answer in its premise.

It seems like a download error.
This system have Internet access?



If there is no Internet access, you can try to add the following line to `nodejs.spec` . (94-96)

```
~~ snip ~~
 88 %if 0%{?rhel} == 5
 89 %patch0 -p1
 90 %patch1 -p1
 91 %patch2 -p1
 92 %endif
 93 
 94 %if 0%{?suse_version} == 1315
 95 %patch3 -p1
 96 %endif
 97 
 98 %if 0%{?rhel} == 7 || 0%{?fedora}
 99 %patch3 -p1
100 %endif
~~ snip ~~
```

This change provides for the ICU use are installed on your system.
(and you need to install `libicu` and `libicu-devel` package.)

**Comment by ZissisT** [comment]
Hi, 

there is internet access available, since 'make' downloads latest LTS from internet before attempting to download  ICU. This does not happen just once, it happens every time I run 'make' and it fails in that step. 
The thing is that this goes behind a company proxy, so maybe I need to set some python proxy variables (I guess it does not use system proxy like the rest ? ).
I will try your workaround and let you know, thanks !

Zissis

**Comment by kazuhisya** [comment]
Ah, I see.

Ｉ don't know why but system proxy settings is seems perhaps not pick up from shell.
Please check `env |grep -i proxy`. and export this setting.

```shell
$ export HTTP_PROXY="http://<PROXY>:<port>"
$ export HTTPS_PROXY="http://<PROXY>:<port>"
```

I would be happy if you let me know the result later.  thank you !

**Comment by ZissisT** [comment]
Hi again,

I already have this exported (env |grep -i proxy returns correct values), but I exported it again as you said. Same happens.
If shell did not see proxy settings then wget of nodejs would fail as well (If I remove proxy settings it fails).
Right now it succeeds:

--2016-09-11 21:01:14--  https://nodejs.org/dist/v4.5.0/node-v4.5.0.tar.gz
Connecting to <myproxy>:8080... connected.
Proxy request sent, awaiting response... 200 OK
Length: 22708609 (22M) [application/gzip]
Saving to: ‘node-v4.5.0.tar.gz’

The error thrown is an ssl error and it seems it is a certificate issue, described here:

http://stackoverflow.com/questions/10667960/python-requests-throwing-up-sslerror

but I don't know how to fix that.
I will now try to install icu manually and change spec like you originally proposed.

Zissis

**Comment by ZissisT** [comment]
...and yes, your workaround worked, it started building eveyrthing :)

But, it does not pakage them in the end, as if a script path issue exists:

```
+ popd
~/gitRepos/nodejs-rpm/dist/BUILD/node-v4.5.0
+ exit 0
Executing(%install): /bin/sh -e /var/tmp/rpm-tmp.tSeknh
+ umask 022
+ cd /home/zissis/gitRepos/nodejs-rpm/dist/BUILD
+ cd node-v4.5.0
+ rm -rf /home/zissis/gitRepos/nodejs-rpm/dist/install
+ mkdir -p /home/zissis/gitRepos/nodejs-rpm/dist/install/usr
+ cp -Rp /home/zissis/gitRepos/nodejs-rpm/dist/SOURCES/node-v4.5.0-linux-x64/CHANGELOG.md /home/zissis/gitRepos/nodejs-rpm/dist/SOURCES/node-v4.5.0-linux-x64/LICENSE /home/zissis/gitRepos/nodejs-rpm/dist/SOURCES/node-v4.5.0-linux-x64/README.md /home/zissis/gitRepos/nodejs-rpm/dist/SOURCES/node-v4.5.0-linux-x64/bin /home/zissis/gitRepos/nodejs-rpm/dist/SOURCES/node-v4.5.0-linux-x64/include /home/zissis/gitRepos/nodejs-rpm/dist/SOURCES/node-v4.5.0-linux-x64/lib /home/zissis/gitRepos/nodejs-rpm/dist/SOURCES/node-v4.5.0-linux-x64/share /home/zissis/gitRepos/nodejs-rpm/dist/install/usr/
+ mkdir -p /home/zissis/gitRepos/nodejs-rpm/dist/install/usr/share/doc/packages/node-v4.5.0/
+ for file in CHANGELOG.md LICENSE README.md
+ mv /home/zissis/gitRepos/nodejs-rpm/dist/install/usr/CHANGELOG.md /home/zissis/gitRepos/nodejs-rpm/dist/install/usr/share/doc/packages/node-v4.5.0/
+ for file in CHANGELOG.md LICENSE README.md
+ mv /home/zissis/gitRepos/nodejs-rpm/dist/install/usr/LICENSE /home/zissis/gitRepos/nodejs-rpm/dist/install/usr/share/doc/packages/node-v4.5.0/
+ for file in CHANGELOG.md LICENSE README.md
+ mv /home/zissis/gitRepos/nodejs-rpm/dist/install/usr/README.md /home/zissis/gitRepos/nodejs-rpm/dist/install/usr/share/doc/packages/node-v4.5.0/
+ mv '/home/zissis/gitRepos/nodejs-rpm/dist/install/usr/share/doc/packages/node/*' /home/zissis/gitRepos/nodejs-rpm/dist/install/usr/share/doc/packages/node-v4.5.0/
mv: cannot stat '/home/zissis/gitRepos/nodejs-rpm/dist/install/usr/share/doc/packages/node/*': No such file or directory
error: Bad exit status from /var/tmp/rpm-tmp.tSeknh (%install)


RPM build errors:
    Bad exit status from /var/tmp/rpm-tmp.tSeknh (%install)
Makefile:12: recipe for target 'rpm' failed
make: *** [rpm] Error 1
```

Directory 'node' is on the same level as 'packages' not inside it.
 I'm attaching full build logs, 

[makeResult.txt](https://github.com/kazuhisya/nodejs-rpm/files/466168/makeResult.txt)

This happens in master branch (v6) as well as the LTS.

Thank you!
Zissis

**Comment by kazuhisya** [comment]
That is correct, just as you said.
I expect that point to `%{_defaultdocdir}` macro is `/usr/share/doc/` . (RHEL/Fedora Defaults)
But, in the case of SUSE system, it seems to point to `/usr/share/doc/packages` .

So I was able to build in following changes.(on openSUSE42.1)

https://gist.github.com/kazuhisya/fdd69b66f584b8f03b97a408f379ee22

Can you try this change? thank you !

**Comment by ZissisT** [comment]
Hello,

It worked ! Thanks a lot ! Now SUSE is supported :)

Regards
Zissis

**Comment by kazuhisya** [comment]
Hi, @ZissisT

Thank you for your report and testing!
I have applied this change(and small refactor) to all branches.
and...I have prepared Dockerfile of opensuse for build-test.( [docker/Dockerfile-suse](https://github.com/kazuhisya/nodejs-rpm/blob/master/docker/Dockerfile-suse) )
