### ISSUE TITLE
LTS branch no longer exist

### ISSUE THREAD

**Issue by Millnert** [kazuhisya/nodejs-rpm#59]
The README.md says:
\# If you want to use the LTS version: git clone -b LTS https://github.com/kazuhisya/nodejs-rpm.git

We use this method in our CI.
Since some day back, the LTS branch no longer exist (and all traces of it ever, seems gone as well).
Which of v4.x and v6.x is the replacement branch?

**Comment by kazuhisya** [comment]
I'm sorry, I forgot to update the README.
Previous `LTS` branch, has been maintained in the `v4.x` branch.


|old branch name| old branch version | new branch name| new branch version |
|---------------|--------------------|----------------|--------------------|
| `master `     | v6.x               | `master`       | v7.x               |
| N/A           | N/A                | `v6.x`         | v6.x               |
| `stable-v5`   | v5.x               | `v5.x`         | v5.x               |
| `LTS`         | v4.x               | `v4.x`         | v4.x               |




Current LTS is available in two versions of 4 and 6. ( [LTS schedule](https://github.com/nodejs/LTS#lts-schedule) )
Therefore I adjust to upstream branch name.
